console:
  max_message_size_bytes: 409600
logger:
  level: "DEBUG"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
iap:
  google:
    client_email: ""
    private_key: ""
publicip: 173.249.58.114
redis: 
  addr: 173.249.58.114:7379
  password: 

